### PR TITLE
t1_brain_denoised_gibbs_unringing after

### PR DESCRIPTION
**Pull request by areeshatariq**

### CODE REVIEW

**Comment by jhlegarreta** [comment]
@skoudoro @ShreyasFadnavis @Garyfallidis is this output showing meaningful enough differences after the Gibbs unringing? I think the dataset used is `sherbrooke_3shell`.

**Comment by areeshatariq** [comment]
> @skoudoro @ShreyasFadnavis @Garyfallidis is this output showing meaningful enough differences after the Gibbs unringing? I think the dataset used is `sherbrooke_3shell`.

The dataset that I used is ``tissue_data``

**Comment by skoudoro** [comment]
I think we should do like the tutorial and point with a red arrow where is the unringing effect. Can you edit this file @areeshatariq

**Comment by areeshatariq** [comment]
> I think we should do like the tutorial and point with a red arrow where is the unringing effect. Can you edit this file @areeshatariq

@skoudoro should I add rings in the uncorrected (before) image like in https://dipy.org/documentation/1.2.0./examples_built/denoise_gibbs?

**Comment by skoudoro** [comment]
yes, you can do that. you remove the high frequencies and then, save the image as a nifti file. This image will be your official  original image. You can replace the one already merged.

**Comment by areeshatariq** [comment]
> yes, you can do that. you remove the high frequencies and then, save the image as a nifti file. This image will be your official original image. You can replace the one already merged.

Alright! Will do this and update the Gibbs unringing draft PR

**Comment by jhlegarreta** [comment]
Looks good to me.

**Review by jhlegarreta — APPROVED** [review]

**Pull request merged**
